development: &default
  adapter: postgresql
  database: vacant_properties_development
  pool: 5
  timeout: 5000
  min_messages: warning

test: &test
  <<: *default
  database: vacant_properties_test

cucumber:
  <<: *test